### PR TITLE
Added global config pyproject.toml

### PR DESCRIPTION
**Pull request by etimoz**
I added a global config `.docformatter.ini `as requested in this issue https://github.com/myint/docformatter/issues/10. 
It is designed in a similar manner to the flake8 config. 

`.docformatter.ini` can be provided on the project level and user's home directory (`~/.docformatter.ini`). 

Run arguments are merged from the command line and config as following:
The command line options have highest priority and override set config options. Project level config overrides the config set in the user's home directory.

### CODE REVIEW

**Comment by ruohola** [comment]
Would it make more sense to instead just support `pyproject.toml`?

**Comment by etimoz** [comment]
I look into it, would probably make sense.

**Comment by etimoz** [comment]
Instead of `.docformatter.ini`now `pyproject.toml` is supported.

**Comment by PhilReinhold** [comment]
This would be really great to have!

**Review by ruohola — APPROVED** [review]

**Review by myint — CHANGES_REQUESTED** [review]
Thanks! I hadn't had time to log into `github.com` in quite a while.

Can you replace the `toml` dependency with Python's built-in functionality? In other projects like `pycodestyle`, the config parsing is handled without additional dependencies.
pycodestyle`, the `.ini`parsing was handled using built-in Python functionality.

**Comment by ruohola** [comment]
@myint But wouldn't the common `pyproject.toml` be more modern and preferable compared to a yet an other random `.ini` file?

**Comment by myint** [comment]
Is `pyproject.toml` fairly standard now? If so, it would seem reasonable to me. It's been a couple years since I've had time to look at open source Python projects.

**Comment by ruohola** [comment]
It is imo, at least `black`, `isort`, `pytest`, `coverage` are already supporting it, and `mypy` should [soon](https://github.com/python/mypy/issues/5205) support it.

**Review by myint — APPROVED** [review]

**Comment by myint** [comment]
Hmm, I merged too soon. I ended up reverting this change in the `master` branch. There are a couple issues i noticed:

- [ ] Running `docformatter` with no options doesn't work like it used to. It ought to print out a help message, but not it outputs a badly formatted line. I'd prefer the new functionality not degrade the existing use cases.
```
✔ myint@macpro:~/projects/docformatter (master *)
$ ./docformatter.py
error: the following arguments are required: files✘ myint@macpro:~/projects/docformatter (master *)
```
- [ ] The linters don't pass (`pydocstyle`, `pycodestyle`, etc.`). The `pylint` findings could be suppressed if you want though. Run `make` to see the errors.

**Comment by etimoz** [comment]
I made the changes in #65 to print out the help message when no argument is provided and the code formatting. If you notice any other issues please let me know.

**Comment by Borda** [comment]
Do we have an example of how to use it or what is the keyword?

**Comment by dabauxi** [comment]
@Borda Please have a look at #65 and there should be a `pyproject.example.toml`.

**Pull request merged**
